

package ChatUI;

import java.io.File;
import java.text.DecimalFormat;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import Client.ChatClient;


public class ChatUI extends javax.swing.JFrame {

  private ChatClient client;
  private final String USER;
  private String RECEIVER;
  private DefaultListModel<String> listModel = new DefaultListModel<>();


  public ChatUI(String user, String receiver) {
    this.USER = user;
    this.RECEIVER = receiver;
    initComponents();
    initService();
  }

  private void initService() {
    client = new ChatClient("127.0.0.1", "/data_client", 8070, USER);

    messageList.setModel(listModel);
    lblUser.setText(USER);
    lblReceptor.setText(RECEIVER);
    this.getRootPane().setDefaultButton(btnSend);

    client.setOnMessageFunction((sender, message) -> {
      listModel.addElement(sender + " : " + message);
    });
    client.setOnSendFileData((receiver, filename, filesize) -> {
      btnChooseFile.setEnabled(false);
      lblReceiver.setText("Envias " + filename + " a: " + receiver);
    });
    client.setOnSendFileBytes(percentage -> {
      senderProgressBar.setValue((int) percentage);
      DecimalFormat decimalFormat = new DecimalFormat("#.##");
      String formattedPercentage = decimalFormat.format(percentage);
      lblSenderPercentage.setText(formattedPercentage + "%");
    });
    client.setOnReceiverFileData((sender, filename, filesize) -> {
      lblSender.setText(sender + " te envia " + filename + ": ");
    });
    client.setOnReceiverFileBytes(percentage -> {
      receiverProgressBar.setValue((int) percentage);
      DecimalFormat decimalFormat = new DecimalFormat("#.##");
      String formattedPercentage = decimalFormat.format(percentage);
      lblReceiverPercentage.setText(formattedPercentage + "%");
    });
    client.setOnEndSendFile(() -> {
      btnChooseFile.setEnabled(true);
    });

    client.start();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    lblUser = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    lblReceptor = new javax.swing.JLabel();
    headerPanel = new javax.swing.JPanel();
    btnChooseFile = new javax.swing.JButton();
    lblReceiver = new javax.swing.JLabel();
    senderProgressBar = new javax.swing.JProgressBar();
    lblSenderPercentage = new javax.swing.JLabel();
    btnNewReceiver = new javax.swing.JButton();
    midPanel = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    messageList = new javax.swing.JList<>();
    jPanel1 = new javax.swing.JPanel();
    lblSender = new javax.swing.JLabel();
    receiverProgressBar = new javax.swing.JProgressBar();
    lblReceiverPercentage = new javax.swing.JLabel();
    bottomPanel = new javax.swing.JPanel();
    txtMessage = new javax.swing.JTextField();
    btnSend = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });
    getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

    jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

    lblUser.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
    lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblUser.setText("user-name");
    jPanel2.add(lblUser);

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
    jLabel1.setText("   -->");
    jPanel2.add(jLabel1);

    lblReceptor.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
    lblReceptor.setText("receiver-name");
    jPanel2.add(lblReceptor);

    getContentPane().add(jPanel2);

    headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

    btnChooseFile.setText("Enviar Archivo");
    btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnChooseFileActionPerformed(evt);
      }
    });
    headerPanel.add(btnChooseFile);
    headerPanel.add(lblReceiver);

    senderProgressBar.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
    headerPanel.add(senderProgressBar);
    headerPanel.add(lblSenderPercentage);

    btnNewReceiver.setText("Nuevo Receptor");
    btnNewReceiver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNewReceiverActionPerformed(evt);
      }
    });
    headerPanel.add(btnNewReceiver);

    getContentPane().add(headerPanel);

    midPanel.setLayout(new javax.swing.BoxLayout(midPanel, javax.swing.BoxLayout.LINE_AXIS));

    jScrollPane1.setMinimumSize(new java.awt.Dimension(270, 270));
    jScrollPane1.setName(""); // NOI18N
    jScrollPane1.setPreferredSize(new java.awt.Dimension(490, 250));

    messageList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(messageList);

    midPanel.add(jScrollPane1);

    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
    jPanel1.add(lblSender);

    receiverProgressBar.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
    jPanel1.add(receiverProgressBar);
    jPanel1.add(lblReceiverPercentage);

    midPanel.add(jPanel1);

    getContentPane().add(midPanel);

    bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

    txtMessage.setPreferredSize(new java.awt.Dimension(490, 37));
    bottomPanel.add(txtMessage);

    btnSend.setText("Enviar");
    btnSend.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSendActionPerformed(evt);
      }
    });
    bottomPanel.add(btnSend);

    getContentPane().add(bottomPanel);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnNewReceiverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNewReceiverActionPerformed
    String receiver = JOptionPane.showInputDialog(null, "Ingresa el nuevo receptor", "Receptor",
        JOptionPane.INFORMATION_MESSAGE);
    if (receiver != null) {
      this.RECEIVER = receiver.trim();
      lblReceptor.setText(RECEIVER);
    }
  }// GEN-LAST:event_btnNewReceiverActionPerformed

  private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChooseFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    int option = fileChooser.showOpenDialog(this);
    if (option == JFileChooser.APPROVE_OPTION) {
      File selectedFile = fileChooser.getSelectedFile();
      client.sendFile(RECEIVER, selectedFile.getAbsolutePath());
    }
  }// GEN-LAST:event_btnChooseFileActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
    client.closeService();
  }// GEN-LAST:event_formWindowClosing

  private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSendActionPerformed
    String message = txtMessage.getText().trim();
    if (!message.isEmpty()) {
      client.sendMessage(RECEIVER, txtMessage.getText().trim());
      txtMessage.setText("");
      listModel.addElement("Tu" + " : " + message);
    }
  }// GEN-LAST:event_btnSendActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ChatUI("cliente_1", "cliente_2").setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bottomPanel;
  private javax.swing.JButton btnChooseFile;
  private javax.swing.JButton btnNewReceiver;
  private javax.swing.JButton btnSend;
  private javax.swing.JPanel headerPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblReceiver;
  private javax.swing.JLabel lblReceiverPercentage;
  private javax.swing.JLabel lblReceptor;
  private javax.swing.JLabel lblSender;
  private javax.swing.JLabel lblSenderPercentage;
  private javax.swing.JLabel lblUser;
  private javax.swing.JList<String> messageList;
  private javax.swing.JPanel midPanel;
  private javax.swing.JProgressBar receiverProgressBar;
  private javax.swing.JProgressBar senderProgressBar;
  private javax.swing.JTextField txtMessage;
  // End of variables declaration//GEN-END:variables
}
